#!/usr/bin/env bash

# Converts flac to 16bit 48kHz

# 16/44.1 is the redbook standard that was chosen for CDs. It wasn't picked randomly, 
# it was selected because it covers (well, exceeds) the range of human hearing.
# 16-bits gives 96dB of dynamic range, 44.1KHz covers 0Hz to 22050Hz.
# When young with perfect hearing, you'll hear 20Hz to 20000Hz.
# Trained listeners have heard differences between 16/44.1 and high res when listening in controlled test environments, using headphones and test tones. 
# Real world, with music, you have no chance of hearing any difference. 
# A million times more so when listening through speakers as you'll have 30-40dB noise floor in a quiet room.
# There are genuine benefits for recording and producing music at higher sample rates and bit depth, but no benefit for music playback.
# If you can hear differences between high res and 16/44.1 versions of a song, they will be different masters.


for f in ./*.flac */*.flac */*/*.flac; do
  [ -e "$f" ] || continue
  rate=$(ffprobe -v error -select_streams a:0 -show_entries stream=sample_rate -of csv=p=0 "$f")
  bits=$(ffprobe -v error -select_streams a:0 -show_entries stream=bits_per_raw_sample -of csv=p=0 "$f")
  bits=${bits:-0}

  if { [ "$rate" -eq 44100 ] || [ "$rate" -eq 48000 ]; } && [ "$bits" -eq 16 ]; then
    echo "$f" already 16bit 44.1-48kHz
    continue
  elif (( rate % 48000 == 0 )); then
    ffmpeg -y -i "$f" -ar 48000 -sample_fmt s16 "${f%.flac} 16_48.flac" 
    rm -f "$f"
  else
    ffmpeg -y -i "$f" -ar 44100 -sample_fmt s16 "${f%.flac} 16_44.flac"
    rm -f "$f"
  fi
done

